<?php
$z[0]=Array("global","",366,393);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",405,437);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",484,510);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("myad","",565,600);
$z[3][4]['name']="innerTopBanner1";
$z[4]=Array("myad","",635,670);
$z[4][4]['name']="innerTopBanner2";
$z[5]=Array("global","",973,998);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",1038,1285);
$z[6][4]['type']="top";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[7]=Array("global","",1377,1402);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2210,2340);
$z[8][4]['row']="10";
$z[8][4]['getall']="1";
$z[8][4]['sort']="month";

?>